#!/bin/bash
# title           :ldap-restore
# description     :Perform LDAP restore on Zarafa server
# author          :Alexander Jackson - Jackson IT
# date            :20141017
# version         :0.1
# usage           :ldap-restore
# notes           :Save in /usr/local/sbin/ chown: root.root chmod: 500
# bash_version    :GNU bash, Version 4.2.37(1)-release (x86_64-pc-linux-gnu)
#
# Copyright 2014, Alexander Jackson <alexander.jackson@jackson-it.de>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License at <http://www.gnu.org/licenses/> for
# more details.
#
#==============================================================================
TIMESTAMP=$(date +%Y%m%d-%H%M%S)
BACKUP_PATH=/var/backups/ldap/
LATEST_BACKUP=$(ls -dt ${BACKUP_PATH}* | head -n 1)
echo
echo + - - - Listing the 7 newest backup folders-------- -------------- - - - +
echo "+ - - - (more backups might be available...) --------------------- - - - +"
echo
ls -dthl ${BACKUP_PATH}* | head -n 6
echo
echo
echo + - - - Select the backup folder from which to restore ----------- - - - +
echo "+ - - - (newest backup selected by default) ---------------------- - - - +"
echo
read -e -p "Enter: [${LATEST_BACKUP}]" BACKUP_PATH
BACKUP_PATH=${BACKUP_PATH:-$LATEST_BACKUP}
echo
echo
echo Folder ${BACKUP_PATH} selected
echo for the restoring procedure.
echo
echo
echo + - - - Are you sure you want to continue? ----------------------- - - - +
echo "+ - - - (you might seriously mess things up continuing) ---------- - - - +"
echo
echo
read -p "Did you make separate backups? You've been warned! Proceed? [y/n] " -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
if [ -z '${BACKUP_PATH}' ];
then
echo
echo + - - - No backup folder provided. Aborting! --------------------- - - - +
echo
else
echo
echo + - - - Creating new backup with ldap-backup script -------------- - - - +
echo "+ - - - (better safe than sorry ...) ----------------------------- - - - +"
echo
ldap-backup
echo
echo + - - - Restoring ------------------------------------------------ - - - +
echo
service slapd stop ; service slapd status # Failing is o.k. because service is down ...
mkdir -p /etc/ldap/slapd.d-backup/ /var/lib/ldap-backup/
cp -a /etc/ldap/slapd.d/ /etc/ldap/slapd.d-backup/${TIMESTAMP} # Additional backup
cp -a /var/lib/ldap/ /var/lib/ldap-backup/${TIMESTAMP} # Additional backup
rm -r /etc/ldap/slapd.d/* /var/lib/ldap/* # Emptying folders
slapadd -F /etc/ldap/slapd.d -n 0 -l ${BACKUP_PATH}/config.ldif # Import LDAP config
slapadd -F /etc/ldap/slapd.d -n 1 -l ${BACKUP_PATH}/domain.ldif # Import DIT data
# mkdir /var/lib/ldap/accesslog
# slapadd -F /etc/ldap/slapd.d -n 2 -l ${BACKUP_PATH}/access.ldif
chown -R openldap:openldap /etc/ldap/slapd.d/ /var/lib/ldap/ # Fixing ownership
service slapd start ; service slapd status # Starting und testing slapd 
echo
echo + - - - INFO ------------------------------------------------------ - - - +
echo
echo "  Manual restore of /etc/ldap and /var/lib/ldap from *.tgz should"
echo "  be possible. Here the additional backup files from your"
echo "  selected backup folder ${BACKUP_PATH}:"
echo
ls ${BACKUP_PATH}/*.tgz
echo
echo "  Two additional backups have been created before the restore attempt."
echo "  You can find theme at:"
echo "  1. /etc/ldap/slapd.d-backup/${TIMESTAMP}"
echo "  2. /var/lib/ldap-backup/${TIMESTAMP}"
echo
echo + - - - ------------------------------------------------------ DONE - - - +
fi
else
echo Aborting!
fi
